name: writing_exchange
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  build_runner: ^2.1.8
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.3
  freezed: ^1.1.1
  freezed_annotation: ^1.1.0
  cupertino_icons: ^1.0.2
  slang: ^3.5.0
  slang_flutter: ^3.5.0
  pretty_diff_text: ^1.0.0
  flutter_staggered_grid_view: ^0.6.2
  firebase_core: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
